//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Reflection;

[assembly: System.Reflection.AssemblyCompanyAttribute("gsscoder;nemec;ericnewton76;moh-hassan")]
[assembly: System.Reflection.AssemblyConfigurationAttribute("Debug")]
[assembly: System.Reflection.AssemblyCopyrightAttribute("Copyright (c) 2005 - 2020 Giacomo Stelluti Scala & Contributors")]
[assembly: System.Reflection.AssemblyDescriptionAttribute("Terse syntax C# command line parser for .NET.  For FSharp support see CommandLine" +
    "Parser.FSharp.  The Command Line Parser Library offers to CLR applications a cle" +
    "an and concise API for manipulating command line arguments and related tasks.")]
[assembly: System.Reflection.AssemblyFileVersionAttribute("0.0.0.0")]
[assembly: System.Reflection.AssemblyInformationalVersionAttribute("0.0.0")]
[assembly: System.Reflection.AssemblyProductAttribute("CommandLine")]
[assembly: System.Reflection.AssemblyTitleAttribute("CommandLine")]
[assembly: System.Reflection.AssemblyVersionAttribute("0.0.0.0")]

// Generado por la clase WriteCodeFragment de MSBuild.

